"""Workflow, status, and exception enums."""

from __future__ import annotations

from enum import StrEnum


class AnalyteType(StrEnum):
    DS_DNA = "dsDNA"
    TOTAL_RNA = "total_RNA"


class WorkflowType(StrEnum):
    DNA_QUANT = "DNA_QUANT"
    DNA_NORMALIZATION = "DNA_NORMALIZATION"
    RNA_NORMALIZATION_REQUANT = "RNA_NORMALIZATION_REQUANT"


class ExceptionSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    BLOCKING = "BLOCKING"


class NormalizationMode(StrEnum):
    STANDARD_NEW_CONTAINER = "STANDARD_NEW_CONTAINER"
    IN_PLACE = "IN_PLACE"
    SPLIT_REQUIRED = "SPLIT_REQUIRED"


class Status(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    EXCLUDED = "EXCLUDED"
    STANDARD_NORMALIZATION = "STANDARD_NORMALIZATION"
    IN_PLACE_NORMALIZATION_SELECTED = "IN_PLACE_NORMALIZATION_SELECTED"
    SPLIT_REQUIRED_HIGH_CONCENTRATION = "SPLIT_REQUIRED_HIGH_CONCENTRATION"
    SPLIT_CREATED = "SPLIT_CREATED"
    SPLIT_REQUANT_REQUIRED = "SPLIT_REQUANT_REQUIRED"
    FOLLOWUP_NORMALIZATION_REQUIRED = "FOLLOWUP_NORMALIZATION_REQUIRED"
    REQUANT_COMPLETE = "REQUANT_COMPLETE"
    DOWNSTREAM_READY = "DOWNSTREAM_READY"
    OUT_OF_RANGE = "OUT_OF_RANGE"


class ExceptionCode(StrEnum):
    MISSING_SAMPLE_ID = "MISSING_SAMPLE_ID"
    DUPLICATE_SAMPLE_ID = "DUPLICATE_SAMPLE_ID"
    MISSING_SOURCE_LOCATION = "MISSING_SOURCE_LOCATION"
    INVALID_SOURCE_LOCATION = "INVALID_SOURCE_LOCATION"
    DUPLICATE_SOURCE_LOCATION = "DUPLICATE_SOURCE_LOCATION"
    MISSING_DESTINATION_LOCATION = "MISSING_DESTINATION_LOCATION"
    INVALID_DESTINATION_LOCATION = "INVALID_DESTINATION_LOCATION"
    DUPLICATE_DESTINATION_LOCATION = "DUPLICATE_DESTINATION_LOCATION"
    DESTINATION_SUPPLIED_FOR_IN_PLACE = "DESTINATION_SUPPLIED_FOR_IN_PLACE"
    MISSING_AVAILABLE_VOLUME = "MISSING_AVAILABLE_VOLUME"
    INVALID_AVAILABLE_VOLUME = "INVALID_AVAILABLE_VOLUME"
    MISSING_CONCENTRATION = "MISSING_CONCENTRATION"
    INVALID_CONCENTRATION = "INVALID_CONCENTRATION"
    UNSUPPORTED_CONCENTRATION_UNIT = "UNSUPPORTED_CONCENTRATION_UNIT"
    SOURCE_CONCENTRATION_BELOW_TARGET = "SOURCE_CONCENTRATION_BELOW_TARGET"
    INSUFFICIENT_SOURCE_VOLUME = "INSUFFICIENT_SOURCE_VOLUME"
    SAMPLE_TRANSFER_BELOW_MINIMUM = "SAMPLE_TRANSFER_BELOW_MINIMUM"
    SAMPLE_TRANSFER_ABOVE_MAXIMUM = "SAMPLE_TRANSFER_ABOVE_MAXIMUM"
    DILUENT_VOLUME_NEGATIVE = "DILUENT_VOLUME_NEGATIVE"
    DESTINATION_VOLUME_EXCEEDED = "DESTINATION_VOLUME_EXCEEDED"
    MISSING_PLATE_BLANK = "MISSING_PLATE_BLANK"
    INVALID_SAMPLE_PLATE_LAYOUT = "INVALID_SAMPLE_PLATE_LAYOUT"
    INVALID_BATCH_STANDARD_CURVE = "INVALID_BATCH_STANDARD_CURVE"
    MISSING_BATCH_STANDARD_CURVE = "MISSING_BATCH_STANDARD_CURVE"
    SPLIT_REQUIRED_HIGH_CONCENTRATION = "SPLIT_REQUIRED_HIGH_CONCENTRATION"
    SPLIT_REQUANT_REQUIRED = "SPLIT_REQUANT_REQUIRED"
    IN_PLACE_NORMALIZATION_SELECTED = "IN_PLACE_NORMALIZATION_SELECTED"
    IN_PLACE_NORMALIZATION_INVALID = "IN_PLACE_NORMALIZATION_INVALID"
    INVALID_REQUANT_RESULT = "INVALID_REQUANT_RESULT"
    MISSING_REQUANT_RESULT = "MISSING_REQUANT_RESULT"
    REQUANT_OUT_OF_ASSAY_RANGE = "REQUANT_OUT_OF_ASSAY_RANGE"
    DOWNSTREAM_VOLUME_CONSTRAINT_FAILED = "DOWNSTREAM_VOLUME_CONSTRAINT_FAILED"
    QC_STATUS_FAILED = "QC_STATUS_FAILED"
    REQUIRED_ARTIFACT_MISSING = "REQUIRED_ARTIFACT_MISSING"


class AncestryEventType(StrEnum):
    QUANTIFIED = "QUANTIFIED"
    NORMALIZED_STANDARD = "NORMALIZED_STANDARD"
    NORMALIZED_IN_PLACE = "NORMALIZED_IN_PLACE"
    SPLIT_CREATED = "SPLIT_CREATED"
    REQUANTIFIED = "REQUANTIFIED"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    EXCLUDED = "EXCLUDED"
